# Generated by Django 3.2.5 on 2021-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_remove_event_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Hong Kong', max_length=255),
            preserve_default=False,
        ),
    ]
