# Generated by Django 3.2.5 on 2021-07-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210730_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
